name: Deploy Messenger

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to, development, staging, production
        required: true
        type: environment
        default: staging

env:
  ECR_REPOSITORY: fastapicloud-messenger

jobs:
  changes:
    runs-on: depot-ubuntu-22.04
    # Required permissions
    permissions:
      pull-requests: read
      contents: read
    # Set job outputs to values from filter step
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
    - uses: actions/checkout@v4
    # For pull requests it's not necessary to checkout the code but for the main branch it is
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          changed:
            - backend/**
            - packages/**
            - uv.lock
            - pyproject.toml
            - .env
            - infra/k8s/messenger/messenger.yaml
            - .github/workflows/deploy-messenger.yml

  deploy-messenger:
    needs:
      - changes
    if: ${{ needs.changes.outputs.changed == 'true' }}
    name: Deploy Messenger
    strategy:
      matrix:
        # Two environments by default: staging and development, but can be overridden by the user in a workflow dispatch
        # TODO: once production is stable, disallow deploying to production from workflow_dispatch
        environment: ${{ github.event_name == 'workflow_dispatch' && fromJson(format('["{0}"]', github.event.inputs.environment)) || fromJson('["staging", "development", "production"]') }}
    env:
      IMAGE_TAG: ${{ matrix.environment }}-${{ github.sha }}
    runs-on: depot-ubuntu-22.04
    # Permissions for Depot Docker build
    permissions:
      contents: read
      id-token: write
    environment: ${{ matrix.environment }}
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
    - uses: azure/k8s-set-context@v4
      with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_DATA }}
    - name: Login to Amazon ECR
      with:
        mask-password: True
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - uses: depot/setup-action@v1
    - name: Build and push Docker images to Amazon ECR
      uses: depot/build-push-action@v1
      id: docker-build
      with:
        project: ${{ vars.DEPOT_PROJECT_ID }}
        push: true
        tags: |
          ${{steps.login-ecr.outputs.registry}}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        context: ./
        file: ./backend/Dockerfile
    - name: Update messenger deployment
      run: envsubst < infra/k8s/messenger/messenger.yaml | kubectl apply -f -
      env:
        IMAGE: ${{steps.login-ecr.outputs.registry}}/${{ env.ECR_REPOSITORY }}@${{ steps.docker-build.outputs.digest }}
        ENVIRONMENT: ${{ matrix.environment }}
        AWS_REGION: "${{ vars.AWS_REGION }}"
        DEPLOYMENTS_BUCKET_NAME: "${{ vars.DEPLOYMENTS_BUCKET_NAME }}"
        AWS_SQS_BUILDER_QUEUE_NAME: "${{ vars.AWS_SQS_BUILDER_QUEUE_NAME }}"
        BUILDER_QUEUE_NAME: "${{ vars.BUILDER_QUEUE_NAME }}"
        BUILDER_API_KEY: "${{ secrets.BUILDER_API_KEY }}"
        BUILDER_API_URL: "${{ vars.BUILDER_API_URL }}"
        MESSENGER_SENTRY_DSN: "${{ vars.MESSENGER_SENTRY_DSN }}"
        LOGFIRE_TOKEN: "${{ secrets.LOGFIRE_TOKEN }}"
        NATS_HOST_NAME: "${{ vars.NATS_HOST_NAME }}"
        NATS_CREDS_JSON_STR: "${{ secrets.NATS_CREDS_JSON_STR }}"
        REDIS_SERVER: "${{ vars.REDIS_SERVER }}"

  # https://github.com/marketplace/actions/alls-green#why
  alls-green-deploy-messenger:  # This job does nothing and is only used for the branch protection
    if: always()
    needs:
      - deploy-messenger
    runs-on: depot-ubuntu-22.04
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: deploy-messenger
